AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false